### ISSUE TITLE
Play next song

### ISSUE THREAD

**Issue by mrzoops** [Gearlux/GDeskTunes#28]
Currently play stops after the initial song and will not automatically move to the next song in the album/playlist/mix.

**Comment by fkuo** [comment]
I had the same problem as @mrzoops. I was able to fix it by disabling the HTML5 player in the Google Music Lab settings.

**Comment by mrzoops** [comment]
Yes! Worked perfectly.

**Comment by Gearlux** [comment]
:-) I am glad you figured this out.
